# Generated by Django 3.2.8 on 2021-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('CarsId', models.AutoField(primary_key=True, serialize=False)),
                ('cars_model', models.CharField(max_length=500)),
                ('cars_price', models.CharField(max_length=500)),
                ('cars_TKZ', models.CharField(max_length=500)),
                ('cars_credit', models.CharField(max_length=500)),
                ('cars_price_credit_in_month', models.CharField(max_length=500)),
                ('cars_meliage', models.CharField(max_length=500)),
                ('cars_date_city', models.CharField(max_length=500)),
            ],
        ),
    ]
